import Sidebar from './Sidebar'
import './userpanel_globals.css'

export const metadata = {
  title: 'پنل کاربری',
  description: 'Generated by create next app',
}

export default function UserLayout({ children }) {
  return (
    <body>
        <div className='flex'>
            <Sidebar/>
        </div>

    </body>
  )
}
