import './userpanel_globals.css'

export const metadata = {
  title: 'پنل کاربری',
  description: 'Generated by create next app',
}

export default function UserLayout({ children }) {
  return (
    <div className='bg-red-400'>
        User Layout
        {children}
    </div>
  )
}
