import MenuMobile from './MenuMobile'
import Sidebar from './Sidebar'
import './userpanel_globals.css'

export const metadata = {
    title: 'پنل کاربری',
    description: 'Generated by create next app',
}

export default function UserLayout({ children }) {
    return (
        <body>
            <div className='flex'>
                <div className='md:flex hidden'> <Sidebar /> </div>
                <div
                    className='md:hidden block fixed bottom-0 pb-5 left-0 right-0'
                    style={{
                        background: "linear-gradient(to top, rgba(0,0,0,0.45), transparent 95%)"
                    }}>
                    <MenuMobile />
                </div>

                <main className='overflow-hidden'>
                    {children}
                </main>
            </div>

        </body>
    )
}
